name: Deploy to Amazon S3

on:
  push:
    branches:
      - main # Se ejecuta cada vez que guardas cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # La región donde creamos el bucket

    - name: Subir archivos a S3
      run: |
        aws s3 sync . s3://portafolio-00-aws --delete --exclude ".git/*" --exclude ".github/*"
